FROM centos:7

# Repos needed for (VOMS and FTS) and WLCG certs
ADD ca.repo /etc/yum.repos.d/ca.repo

RUN yum install -y epel-release.noarch http://linuxsoft.cern.ch/wlcg/centos7/x86_64/wlcg-repo-1.0.0-1.el7.noarch.rpm && \
    yum clean all && \
    rm -rf /var/cache/yum

# Configure yum to skip unavailable repositories
RUN yum-config-manager --save --setopt=wlcg.skip_if_unavailable=true

RUN yum update -y && \
    yum upgrade -y && \
    yum clean all && \
    rm -rf /var/cache/yum

# Temporarily disable IUS repository
RUN yum install -y httpd libaio gcc  \
    python36 python36-pip python36-mod_wsgi python36-devel python36-setuptools python36-requests python36-m2crypto mod_ssl  \
    openssl-devel libnsl patch xrootd-client && \
    yum clean all && \
    rm -rf /var/cache/yum

# Install latest kubectl
RUN curl -o /usr/bin/kubectl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x /usr/bin/kubectl

# Install VOMS and FTS clients for delegating proxies
RUN yum -y install ca-certificates.noarch lcg-CA ca_* fetch-crl voms-clients-cpp fts-rest-cli \
    wlcg-iam-lsc-atlas wlcg-iam-vomses-atlas wlcg-voms-atlas wlcg-iam-lsc-cms wlcg-iam-vomses-cms wlcg-voms-cms && \
    yum clean all && \
    rm -rf /var/cache/yum

# Install wget
RUN yum -y install wget && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN python3 -m pip install --no-cache-dir --upgrade pip
RUN python3 -m pip install --no-cache-dir --upgrade setuptools
RUN python3 -m pip install --no-cache-dir j2cli

RUN mkdir -p /opt/rucio/certs/
RUN mkdir -p /opt/rucio/kubeconfig/
RUN mkdir -p -m 775 /opt/rucio/fts-delegate/

ADD docker-entrypoint.sh /opt/rucio/fts-delegate/
ADD renew_fts_proxy.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_atlas.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_dteam.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_tutorial.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_multi_vo.sh.j2 /opt/rucio/fts-delegate/
ADD renew_fts_proxy_escape.sh.j2 /opt/rucio/fts-delegate/

ADD vomses/* /etc/vomses/

ENTRYPOINT ["/opt/rucio/fts-delegate/docker-entrypoint.sh"]
